config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :gigs
   root "gigs#index"
end

app/models/ability.rb
class Ability<ActiveRecord::Base
	belongs_to :gig, optional: true
	belongs_to :skill , optional: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category<ActiveRecord::Base
	has_many :gigs 

end

app/models/gig.rb
class Gig<ActiveRecord::Base
	has_many :proposals
	belongs_to :user, optional: true
	belongs_to :category, optional: true
	has_many :abilities
	has_many :skills, through: :abilities 

end

app/models/proposal.rb
class Proposal<ActiveRecord::Base
	  belongs_to :gig, optional: true
	  belongs_to :user, optional: true
end

app/models/skill.rb
class Skill<ActiveRecord::Base
	 has_many :abilities
	 has_many :gigs, through: :abilities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :gigs
  has_many :proposals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
	def index 
		@gigs = Gig.all.order("created_at DESC").page(params[:page]).per(25)
	end

	def new 
		@gig = Gig.new
	end
	def create
		@gig = Gig.new(gig_params)
		@gig.save
		redirect_to @gig

	end
	def show
		@gig = Gig.find(params[:id])
	end

	def delete

	end

	private

	def gig_params
		params.require(:gig).permit(:name, :description, :budget, :location, :open)
	end

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gigs/_alljob.html.erb
 <table class="table table-hover">
    <thead>
      <tr>
        <th>Job name</th>
        <th>Job Description</th>
        <th>Job Budget</th>
        <th>Job Location</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @gigs.each do |gig| %>
        <td><h5><%= link_to gig.name , gig  %></h5> </td>
        <td><h5><%= gig.description %></h5></td>
        <td><h5>$<%= gig.budget %></h5></td>
        <td><h5><h5><%= gig.location %></h5> </td>

  		
      </tr>
      <% end %>
    </tbody>
  </table>		
  <%= paginate @gigs %>

app/views/gigs/_client_say.html.erb
<div class="client_say"> 

		<h3 class="text-center">What Client say</h3>
	 
			<div class="col-md-4">
				<blockquote>
					<div class="box_aside img-circle">


						<div class="img-circle">
							<svg width="100" height="100">
							  <circle cx="50" cy="50" r="40" stroke="#31b0d5" stroke-width="4" fill="#888" />
							</svg>
						</div>

					</div>
					<div class="box_cnt__no-flow">
						 
						 <h4>There are many variations of passages of Lorem Ipsum available, but the majority  </h4>
						 <cite>Ana</cite>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>

						 
					</div>
				</blockquote> 
			</div>
			<div class="col-md-4">
				<blockquote>
					<div class="box_aside img-circle">
						<div class="img-circle">
							<svg width="100" height="100">
							  <circle cx="50" cy="50" r="40" stroke="#31b0d5" stroke-width="4" fill="#888" />
							</svg>
						</div>
					</div>
					<div class="box_cnt__no-flow">
						 
						  <h4>Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words</h4>
						 <cite>Milica</cite>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
					</div>
				</blockquote> 
			</div>
			<div class="col-md-4">
				<blockquote>
					<div class="box_aside img-circle">
						<div class="img-circle">
							<svg width="100" height="100">
							  <circle cx="50" cy="50" r="40" stroke="#31b0d5" stroke-width="4" fill="#888" />
							</svg>
						</div>
					</div>
					<div class="box_cnt__no-flow">
						 
						 <h4>Have suffered alteration in some form, by injected humour, or randomised words which look even</h4>
						 <cite>Suza</cite>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
						<i class="fa fa-star" aria-hidden="true"></i>
					</div>
				</blockquote> 
			</div>
 </div>
 

app/views/gigs/_form.html.erb
<div class="container">
  <%= form_for @gig do |f| %>
  <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control input-lg" %>
          <small>Title of your job (example: Web developer)</small>
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control input-lg" %>
           <small>Description of your job (example: need Web developer for one month)</small>
        </div>
      </div>
  </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="form-group">
          <%= f.label :budget %>
          <%= f.text_field :budget, class: "form-control input-lg" %>
           <small>Budget for your job (example: $ 1000)</small>
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <div class="form-group">
         <%= f.label :location %>
          <%= f.text_field :location, class: "form-control input-lg" %>
           <small>Job location (example: Los Angeles)</small>
        </div>
      </div>
  </div>
  <%= f.submit class: "btn btn-primary input-lg" %>
  <% end %>
</div>

app/views/gigs/_sidebar.html.erb
<div class="panel">
	<div class="panel-header">
		<div class="panel-body">
		<h3 class="text-center">Last Job</h3>
		 	<ol>
				<% @gigs.last(10).each do |gig| %>
			       <li> <h5><%= link_to gig.name , gig  %></h5>  </li>
			         <h5><%= gig.description %></h5> 
			         <h5>budget: $<%= gig.budget %></h5> 
			         <h5><%= gig.location %></h5> 
			     
			      <% end %>

			</ol> 
		</div>
	</div>
</div>

app/views/gigs/index.html.erb
<div class="alljob">
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<%= render "gigs/alljob.html.erb" %>

			</div>
			<div class="col-md-3">
				<%= render "gigs/sidebar.html.erb" %>
			</div> 
		</div> 
	</div> 

 </div>
	<div class="container">
		 <div class="row">
			<%= render "gigs/client_say" %>
    </div>
	</div>
	

app/views/gigs/new.html.erb
<div class="post-job">
	<div class="container">
		<div class="row">
				<div class="col-md-12">
					<h1>Post a Job</h1>
				</div>
				<%= render "gigs/form" %>
		</div>

	</div>
</div>

app/views/gigs/show.html.erb
<div class="container">
	<div class="panel">
		<div class="panel-header">
			<div class="panel-body">
				 
					<h1> <%= @gig.name %></h1>
					<p><%= @gig.description %></p>
					<p>$ <%= @gig.budget %></p>
					<p><%= @gig.location %></p>

				 
			</div>
		</div>
	</div>
</div>	
	

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron">
	<div class="overlay">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1>Find new Awesome Job</h1>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'New Job', root_path, class: "navbar-brand" %>
          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path, class: "navbar=brand" %></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="navbar-right">
           <% if user_signed_in? %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-info navbar-btn" %>
            <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-warning navbar-btn", method: :delete %>
            <%= link_to "Post a Job", new_gig_path, class: "btn btn-success" %>
            <% else %>
             <%= link_to "Sign In", new_user_session_path, class: "btn btn-defalt navbar-btn" %>
             <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-defalt navbar-btn" %>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/jumbotron' %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>